In [66]:
import pandas as pd
import numpy as np
import os
from numpy import random
import scipy 
from scipy import stats
from matplotlib import pyplot as plt
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import norm ,t
import seaborn as sns
import pylab
from pylab import legend,plot,show,title,xlabel,ylabel
from random import choice
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.stats import proportion  as ssp
from scipy.stats import chisquare
from scipy.stats import chi2_contingency
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels import discrete
from statsmodels.discrete import discrete_model
from statsmodels.discrete.discrete_model import MNLogit
from statsmodels.miscmodels.ordinal_model import OrderedModel
import statsmodels.formula.api as smf
from statsmodels.discrete.discrete_model import Poisson as psn
from statsmodels.discrete.discrete_model import NegativeBinomial as ngb
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import mutual_info_classif
from sklearn.feature_selection import SelectKBest
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# PCA (Principal Component Analysis)

In [68]:
df = pd.read_excel('CDAC_Databook.xlsx', sheet_name='iris')

In [69]:
x = df.drop('Species', axis = 1)
y = df['Species']

In [70]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=20)

In [71]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [72]:
from sklearn.decomposition import PCA

In [73]:
pc_mod = PCA(n_components=2)

x_train = pc_mod.fit_transform(x_train)
x_test = pc_mod.transform(x_test)

The fit(data) method is used to compute the mean and std dev for a given feature to be used further for scaling. The transform(data) method is used to perform scaling using mean and std dev calculated using the . fit() method. The fit_transform() method does both fits and transform.

In [75]:
exp_var = pc_mod.explained_variance_ratio_

The values as output denotes the % of variation among the 4 dimensions when they are reduced to 2 dimensions.

In [77]:
exp_var

array([0.72756536, 0.23418645])

In [78]:
mod1 = DecisionTreeClassifier(max_depth=3)
mod1.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=3)

In [79]:
y_pred = mod1.predict(x_test)

In [80]:
print(confusion_matrix(y_test, y_pred))
print("\n******************************************************\n")
print(classification_report(y_test, y_pred))

[[12  0  0]
 [ 0 11  3]
 [ 0  3  9]]

******************************************************

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.79      0.79      0.79        14
 Iris-virginica       0.75      0.75      0.75        12

       accuracy                           0.84        38
      macro avg       0.85      0.85      0.85        38
   weighted avg       0.84      0.84      0.84        38



- Now, what would be the accuracy if we didn't reduced dimensions? Lets find out:

In [82]:
df = pd.read_excel('CDAC_Databook.xlsx', sheet_name='iris')
x = df.drop('Species', axis = 1)
y = df['Species']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=20)

In [83]:
mod2 = DecisionTreeClassifier(max_depth=3)
mod2.fit(x_train, y_train)
y_pred = mod2.predict(x_test)

In [84]:
print(confusion_matrix(y_test, y_pred))
print("\n******************************************************\n")
print(classification_report(y_test, y_pred))

[[12  0  0]
 [ 0 14  0]
 [ 0  3  9]]

******************************************************

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.82      1.00      0.90        14
 Iris-virginica       1.00      0.75      0.86        12

       accuracy                           0.92        38
      macro avg       0.94      0.92      0.92        38
   weighted avg       0.93      0.92      0.92        38



In [85]:
df = pd.read_excel('CDAC_Databook.xlsx', sheet_name='iris')
x = df.drop('Species', axis = 1)
y = df['Species']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=20)

In [86]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

pc_mod = PCA(n_components=3)

x_train = pc_mod.fit_transform(x_train)
x_test = pc_mod.transform(x_test)

exp_var = pc_mod.explained_variance_ratio_
exp_var

array([0.72756536, 0.23418645, 0.0328708 ])

# LDA (Linear Discriminant Analysis)

In [88]:
df = pd.read_excel('CDAC_Databook.xlsx', sheet_name='iris')
x = df.drop('Species', axis = 1)
y = df['Species']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=20)

In [89]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


In [90]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [91]:
ida_mod = LinearDiscriminantAnalysis()
x_train = ida_mod.fit_transform(x_train, y_train)
x_test = ida_mod.transform(x_test)

In [92]:
mod3 = DecisionTreeClassifier(max_depth=3)
mod3.fit(x_train, y_train)
y_pred = mod3.predict(x_test)

In [93]:
print(confusion_matrix(y_test, y_pred))
print("\n******************************************************\n")
print(classification_report(y_test, y_pred))

[[12  0  0]
 [ 0 14  0]
 [ 0  1 11]]

******************************************************

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.93      1.00      0.97        14
 Iris-virginica       1.00      0.92      0.96        12

       accuracy                           0.97        38
      macro avg       0.98      0.97      0.97        38
   weighted avg       0.98      0.97      0.97        38



## Covariance

In [95]:
a = np.array([4,6,5,7,8])
b = np.array([3,4,2,6,9])

In [96]:
np.cov(a,b)

array([[2.5, 4. ],
       [4. , 7.7]])

In [97]:
np.var(a, ddof=1)

2.5

In [98]:
np.var(b, ddof = 1)

7.7