In [1]:
import pandas as pd
import numpy as np
import os
from numpy import random
import scipy 
from scipy import stats
from matplotlib import pyplot as plt
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import norm ,t
import seaborn as sns
import pylab
from pylab import legend,plot,show,title,xlabel,ylabel
from random import choice
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.stats import proportion  as ssp
from scipy.stats import chisquare
from scipy.stats import chi2_contingency
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels import discrete
from statsmodels.discrete import discrete_model
from statsmodels.discrete.discrete_model import MNLogit
from statsmodels.miscmodels.ordinal_model import OrderedModel
import statsmodels.formula.api as smf
from statsmodels.discrete.discrete_model import Poisson as psn
from statsmodels.discrete.discrete_model import NegativeBinomial as ngb
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.feature_selection import mutual_info_classif
from sklearn.feature_selection import SelectKBest
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

# Supervised Learning:
### Types of Supervised Learning:
1. KNN (k-nearest neighbor algorithm):
- To find the distance we need to use euclidean distance formula --->  d = √[(x2 – x1)2 + (y2 – y1)2].
- Scaling is requried because so that the effect of large numbers does not over shadow the effect of small numbers, Eg --> Age does not pver shadow salary.
- When we take large value of K will lead to under-fitting so model said to be too general, missing out on immportant patterns.
- When we take small value of K will lead to over-fitting so model said to be too specfic 
2. Naive Bayes
3. SVM (Support Vector Machine)

## KNN

In [4]:
df = pd.read_excel('CDAC_DataBook.xlsx',sheet_name='iris')

In [6]:
x = df.drop('Species',axis=1)
y = df.Species

In [8]:
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.2,random_state=20)

In [10]:
mod1 = KNeighborsClassifier(n_neighbors=5).fit(x_train,y_train)

In [12]:
y_pred = mod1.predict(x_test)

In [14]:
print(confusion_matrix(y_pred,y_test))

[[ 8  0  0]
 [ 0 10  0]
 [ 0  1 11]]


In [16]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       1.00      0.91      0.95        11
 Iris-virginica       0.92      1.00      0.96        11

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30



In [18]:
mod2 = KNeighborsClassifier(n_neighbors=2).fit(x_train,y_train)
y_pred1 = mod2.predict(x_test)
print(confusion_matrix(y_pred1,y_test))

[[ 8  0  0]
 [ 0 10  2]
 [ 0  1  9]]


In [20]:
print(classification_report(y_test,y_pred1))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       0.83      0.91      0.87        11
 Iris-virginica       0.90      0.82      0.86        11

       accuracy                           0.90        30
      macro avg       0.91      0.91      0.91        30
   weighted avg       0.90      0.90      0.90        30



In [22]:
8 / (8+0) # recall --> Iris-setosa

1.0

In [24]:
8 / (8+0) # precision --> Iris-setosa

1.0

In [26]:
10 / (10+1) # recall --> Iris-versicolor

0.9090909090909091

In [28]:
10 / (10+2) # precision --> Iris-versicolor

0.8333333333333334

In [30]:
9 / (9+2) # recall --> Iris-virginica

0.8181818181818182

In [32]:
9 / (9+ 1) # precision  --> Iris-virginica

0.9

## Naive Bayes

In [35]:
mod3 = GaussianNB().fit(x_train, y_train)

In [37]:
y_pred = mod3.predict(x_test)

In [39]:
print(confusion_matrix(y_test, y_pred))

[[ 8  0  0]
 [ 0 11  0]
 [ 0  2  9]]


## SVM (Support Vector Machine)

In [42]:
from sklearn import svm

In [46]:
svc1 = svm.SVC(kernel='rbf', C=1) # Linear or Poly are other options

In [48]:
mod4 = svc1.fit(x_train, y_train)